# Generated by Django 6.0.5 on 2026-05-24 16:36

from django.db import migrations, models


def populate_existing_token_metadata(apps, _schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Prediction = apps.get_model("payments", "Prediction")

    Payment.objects.filter(token_address="").update(
        token_symbol="WETH",
        token_address="0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        token_decimals=18,
    )
    Prediction.objects.filter(token_address="").update(
        token_symbol="WETH",
        token_address="0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        token_decimals=18,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_prediction_activity_payment_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='payment',
            name='token_decimals',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='payment',
            name='token_symbol',
            field=models.CharField(default='WETH', max_length=20),
        ),
        migrations.AddField(
            model_name='prediction',
            name='token_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='prediction',
            name='token_decimals',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='prediction',
            name='token_symbol',
            field=models.CharField(default='WETH', max_length=20),
        ),
        migrations.RunPython(populate_existing_token_metadata, migrations.RunPython.noop),
    ]
